### PR TITLE
Fix csv timing

### PR DESCRIPTION
**Pull request by HenningSE**
This PR will try to solve the problems described in https://github.com/XENONnT/fuse/issues/136

### CODE REVIEW

**Comment by KaraMelih** [comment]
Okay, checking this and the source rate change seems to be working. However, I have another (potentially silly) question; <br>
In the examples why is the radius sampled within 50cm and the z is within 150 cm? <br>
I think they both should be in millimeters right? If I run the example and look at the x,y,z distributions they are within 5cm radius and 15 cm depth. <br>

I think it does not harm, but it is potentially misleading.

**Comment by ramirezdiego** [comment]
Hey @KaraMelih, from my side please go ahead and add this information to the notebook.

**Comment by HenningSE** [comment]
Sounds good! Please note that I change the conversion from seconds to nanoseconds with he commit. The user now needs to provide times in nanoseconds which is easier I think.

**Comment by KaraMelih** [comment]
Alright, thanks both! I set the radius to be 66cm, and z-depth to be 150 cm. I also added some comments hoping that it would clarify things. Now, I'm off to go put fuse-developer on my cv.

**Pull request merged**
