### PR TITLE
Test full chain in multiple chunks and clean up input tests

### PR DESCRIPTION
**Pull request by mhliu0001**
Previously, the tests only simulated one chunk. This PR adds tests for multiple chunks.

Also, this PR rewrites `test_input.py` to capture exceptions more elegantly.

### CODE REVIEW

**Comment by mhliu0001** [comment]
I will add some more tests to increase the coverage.

**Comment by HenningSE** [comment]
Hi @mhliu0001, what is the status of this PR?

**Comment by mhliu0001** [comment]
Hi @HenningSE , I think this can be merged now if you want. My original plan was to add some tests with empty instructions, but for the moment this is not the priority.

**Comment by HenningSE** [comment]
Thanks for the PR @mhliu0001 . I re-enabled the single chunk full chain tests (more tests won't hurt us) and will merge this PR when the checks are successful. We can add more tests like you suggested in future PRs.

**Review by HenningSE — APPROVED** [review]

**Pull request merged**
