### PR TITLE
Add a dtypes manger

### PR DESCRIPTION
**Pull request by dachengx**
Similar to https://github.com/XENONnT/fuse/pull/147, but I added a type manager for all plugins.

1. please look at `fuse/dtypes.py` for all lists of fields
2. remove `". Will be set later"` from dtype of `clustered_interactions`
3. add `csv_input_fields` indicating the needed fields for `ChunkCsvInput`

This PR will also remove the trouble of updating the same field distributed in different files later.

### CODE REVIEW

**Comment by dachengx** [comment]
@HenningSE Should this be `float64` or `int64`? https://github.com/XENONnT/fuse/blob/383aab0b4d5c4ff2f48fa60654a8460139945019/fuse/dtypes.py#L5

**Comment by HenningSE** [comment]
> @HenningSE Should this be `float64` or `int64`?
> 
> https://github.com/XENONnT/fuse/blob/383aab0b4d5c4ff2f48fa60654a8460139945019/fuse/dtypes.py#L5

Good catch! This should be an `int64`.

**Review by HenningSE — APPROVED** [review]
Thanks for the nice PR! All working fine!

**Comment by ramirezdiego** [comment]
@dachengx Super nice :)

**Pull request merged**
